In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset= pd.read_csv("preprocessed_Rainfall_dataset.csv")

In [3]:
dataset

day  pressure  maxtemp  temparature  mintemp  dewpoint  humidity  cloud  \
0      1    1025.9     19.9         18.3     16.8      13.1        72     49   
1      2    1022.0     21.7         18.9     17.2      15.6        81     83   
2      3    1019.7     20.3         19.3     18.0      18.4        95     91   
3      4    1018.9     22.3         20.6     19.1      18.8        90     88   
4      5    1015.9     21.3         20.7     20.2      19.9        95     81   
..   ...       ...      ...          ...      ...       ...       ...    ...   
361   27    1022.7     18.8         17.7     16.9      15.0        84     90   
362   28    1026.6     18.6         17.3     16.3      12.8        75     85   
363   29    1025.9     18.9         17.7     16.4      13.3        75     78   
364   30    1025.3     19.2         17.3     15.2      13.3        78     86   
365   31    1026.4     20.5         17.8     15.5      13.0        74     66   

    rainfall  sunshine  winddirection  windspeed  
0        yes       9.3           80.0       26.3  
1        yes       0.6           50.0       15.3  
2        yes       0.0           40.0       14.2  
3        yes       1.0           50.0       16.9  
4        yes       0.0           40.0       13.7  
..       ...       ...            ...        ...  
361      yes       0.0           30.0       18.4  
362      yes       1.0           20.0       25.9  
363      yes       4.6           70.0       33.4  
364      yes       1.2           20.0       20.9  
365       no       5.7           20.0       23.3  

[366 rows x 12 columns]

In [4]:
dataset.isnull().sum()

day              0
pressure         0
maxtemp          0
temparature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
rainfall         0
sunshine         0
winddirection    0
windspeed        0
dtype: int64

In [5]:
# Step 1: Convert 'rainfall' to binary (if not already done)
dataset['rainfall'] = dataset['rainfall'].apply(lambda x: 1 if x == 'yes' else 0)

In [6]:
dataset

day  pressure  maxtemp  temparature  mintemp  dewpoint  humidity  cloud  \
0      1    1025.9     19.9         18.3     16.8      13.1        72     49   
1      2    1022.0     21.7         18.9     17.2      15.6        81     83   
2      3    1019.7     20.3         19.3     18.0      18.4        95     91   
3      4    1018.9     22.3         20.6     19.1      18.8        90     88   
4      5    1015.9     21.3         20.7     20.2      19.9        95     81   
..   ...       ...      ...          ...      ...       ...       ...    ...   
361   27    1022.7     18.8         17.7     16.9      15.0        84     90   
362   28    1026.6     18.6         17.3     16.3      12.8        75     85   
363   29    1025.9     18.9         17.7     16.4      13.3        75     78   
364   30    1025.3     19.2         17.3     15.2      13.3        78     86   
365   31    1026.4     20.5         17.8     15.5      13.0        74     66   

     rainfall  sunshine  winddirection  windspeed  
0           1       9.3           80.0       26.3  
1           1       0.6           50.0       15.3  
2           1       0.0           40.0       14.2  
3           1       1.0           50.0       16.9  
4           1       0.0           40.0       13.7  
..        ...       ...            ...        ...  
361         1       0.0           30.0       18.4  
362         1       1.0           20.0       25.9  
363         1       4.6           70.0       33.4  
364         1       1.2           20.0       20.9  
365         0       5.7           20.0       23.3  

[366 rows x 12 columns]

In [7]:
dataset = pd.get_dummies(dataset,dtype =int,drop_first = True)

In [8]:
dataset

day  pressure  maxtemp  temparature  mintemp  dewpoint  humidity  cloud  \
0      1    1025.9     19.9         18.3     16.8      13.1        72     49   
1      2    1022.0     21.7         18.9     17.2      15.6        81     83   
2      3    1019.7     20.3         19.3     18.0      18.4        95     91   
3      4    1018.9     22.3         20.6     19.1      18.8        90     88   
4      5    1015.9     21.3         20.7     20.2      19.9        95     81   
..   ...       ...      ...          ...      ...       ...       ...    ...   
361   27    1022.7     18.8         17.7     16.9      15.0        84     90   
362   28    1026.6     18.6         17.3     16.3      12.8        75     85   
363   29    1025.9     18.9         17.7     16.4      13.3        75     78   
364   30    1025.3     19.2         17.3     15.2      13.3        78     86   
365   31    1026.4     20.5         17.8     15.5      13.0        74     66   

     rainfall  sunshine  winddirection  windspeed  
0           1       9.3           80.0       26.3  
1           1       0.6           50.0       15.3  
2           1       0.0           40.0       14.2  
3           1       1.0           50.0       16.9  
4           1       0.0           40.0       13.7  
..        ...       ...            ...        ...  
361         1       0.0           30.0       18.4  
362         1       1.0           20.0       25.9  
363         1       4.6           70.0       33.4  
364         1       1.2           20.0       20.9  
365         0       5.7           20.0       23.3  

[366 rows x 12 columns]

In [9]:
dataset["rainfall"].value_counts()

rainfall
1    249
0    117
Name: count, dtype: int64

In [10]:
dataset.columns

Index(['day', 'pressure', 'maxtemp', 'temparature', 'mintemp', 'dewpoint',
       'humidity', 'cloud', 'rainfall', 'sunshine', 'winddirection',
       'windspeed'],
      dtype='object')

In [11]:
independent = dataset[['day', 'pressure', 'maxtemp', 'temparature', 'mintemp', 'dewpoint',
                'humidity', 'cloud','sunshine', 'winddirection','windspeed']]

In [12]:
independent

day  pressure  maxtemp  temparature  mintemp  dewpoint  humidity  cloud  \
0      1    1025.9     19.9         18.3     16.8      13.1        72     49   
1      2    1022.0     21.7         18.9     17.2      15.6        81     83   
2      3    1019.7     20.3         19.3     18.0      18.4        95     91   
3      4    1018.9     22.3         20.6     19.1      18.8        90     88   
4      5    1015.9     21.3         20.7     20.2      19.9        95     81   
..   ...       ...      ...          ...      ...       ...       ...    ...   
361   27    1022.7     18.8         17.7     16.9      15.0        84     90   
362   28    1026.6     18.6         17.3     16.3      12.8        75     85   
363   29    1025.9     18.9         17.7     16.4      13.3        75     78   
364   30    1025.3     19.2         17.3     15.2      13.3        78     86   
365   31    1026.4     20.5         17.8     15.5      13.0        74     66   

     sunshine  winddirection  windspeed  
0         9.3           80.0       26.3  
1         0.6           50.0       15.3  
2         0.0           40.0       14.2  
3         1.0           50.0       16.9  
4         0.0           40.0       13.7  
..        ...            ...        ...  
361       0.0           30.0       18.4  
362       1.0           20.0       25.9  
363       4.6           70.0       33.4  
364       1.2           20.0       20.9  
365       5.7           20.0       23.3  

[366 rows x 11 columns]

In [13]:
dependent = dataset[["rainfall"]]

In [14]:
dependent

rainfall
0           1
1           1
2           1
3           1
4           1
..        ...
361         1
362         1
363         1
364         1
365         0

[366 rows x 1 columns]

In [15]:
independent.shape

(366, 11)

In [16]:
dependent.shape

(366, 1)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.30,random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [19]:
from sklearn.linear_model import LogisticRegression


In [20]:
from sklearn.model_selection import GridSearchCV
param_grid = {'solver':['liblinear','lbfgs','saga','newton-cg'],'penalty':['l2']}
grid = GridSearchCV (LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring = 'f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['liblinear', 'lbfgs', 'saga', 'newton-cg']},
             scoring='f1_weighted', verbose=3)

In [21]:
re = grid.cv_results_
grid_prediction = grid.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,grid_prediction)

In [23]:
from sklearn.metrics import classification_report
clf_report= classification_report(y_test,grid_prediction)

In [24]:
from sklearn.metrics import f1_score
f1_macro= f1_score(y_test,grid_prediction,average = 'weighted')
print("Thef1_macro of best parameter{}:",format(grid.best_params_),f1_macro)

Thef1_macro of best parameter{}: {'penalty': 'l2', 'solver': 'lbfgs'} 0.855514792501094


In [25]:
print("The confusion_matrix:\n",cm)

The confusion_matrix:
 [[29  7]
 [ 9 65]]


In [26]:
print ("The classification_report:\n",clf_report)

The classification_report:
               precision    recall  f1-score   support

           0       0.76      0.81      0.78        36
           1       0.90      0.88      0.89        74

    accuracy                           0.85       110
   macro avg       0.83      0.84      0.84       110
weighted avg       0.86      0.85      0.86       110



In [27]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9121621621621622

In [28]:
table = pd.DataFrame.from_dict(re)

In [29]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       0.008312      0.001296         0.010117        0.001201            l2   
1       0.011925      0.002503         0.009586        0.001031            l2   
2       0.009718      0.003037         0.007315        0.001917            l2   
3       0.007744      0.001400         0.008494        0.000676            l2   

  param_solver                                    params  split0_test_score  \
0    liblinear  {'penalty': 'l2', 'solver': 'liblinear'}           0.760083   
1        lbfgs      {'penalty': 'l2', 'solver': 'lbfgs'}           0.760083   
2         saga       {'penalty': 'l2', 'solver': 'saga'}           0.760083   
3    newton-cg  {'penalty': 'l2', 'solver': 'newton-cg'}           0.760083   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.854611           0.764706           0.840087           0.836172   
1           0.854611           0.782354           0.840087           0.836172   
2           0.854611           0.782354           0.840087           0.836172   
3           0.854611           0.782354           0.840087           0.836172   

   mean_test_score  std_test_score  rank_test_score  
0         0.811132        0.040292                4  
1         0.814662        0.036682                1  
2         0.814662        0.036682                1  
3         0.814662        0.036682                1

In [30]:
day_input = int(input("Day:"))
pressure_input = float(input("Pressure:"))
maxtemp_input = float(input("Maxtemp:"))
temparature_input = float(input("Temparature:"))
mintemp_input = float(input("Mintemp:"))
dewpoint_input = float(input("Dewpoint:"))
humidity_input = int(input("Humidity:"))
cloud_input = int(input("Cloud:"))
sunshine_input = float(input("Sunshine:"))
winddirection_input = float(input("Winddirection:"))
windspeed_input = float(input("Windspeed:"))

Day: 30
Pressure: 1030.5
Maxtemp: 20.4
Temparature: 18.9
Mintemp: 14.5
Dewpoint: 12.7
Humidity: 80
Cloud: 70
Sunshine: 5.5
Winddirection: 24.6
Windspeed: 25.5


In [68]:
Future_prediction = grid.predict([[day_input,pressure_input,maxtemp_input,temparature_input,
                                   mintemp_input,dewpoint_input,humidity_input,cloud_input,
                                   sunshine_input,winddirection_input,windspeed_input]])

In [70]:
Future_prediction

array([1], dtype=int64)

In [72]:
import pickle

In [82]:
filename = "Finalaized_model_LogisticClassifier-Grid.sav"

In [84]:
pickle.dump(grid,open(filename,'wb'))

In [86]:
loaded_model = pickle.load(open("Finalaized_model_LogisticClassifier-Grid.sav",'rb'))

In [88]:
result = loaded_model.predict([[30,1234.5,20.4,32,45.6,78.5,32,12.5,43.6,12,20.4]])

In [90]:
result

array([1], dtype=int64)